---

- name: enable saml20-idp
  replace:
    dest: "{{ ssp_dirname }}/config/config.php"
    regexp: "'enable\\.saml20-idp'\\s*=>.*,"
    replace: "'enable.saml20-idp' => true,"

- name: copy metadata config files
  copy:
    src: "{{ item.filename }}"
    dest: "{{ ssp_dirname }}/{{ item.destdir }}/{{ item.filename }}"
    owner: root
    group: www-data
  with_items:
    - { filename: "authsources.php", destdir: "config" }
    - { filename: "saml20-idp-hosted.php", destdir: "metadata" }

- name: enable exampleauth
  file:
    path: "{{ ssp_dirname }}/modules/exampleauth/enable"
    state: touch
    owner: root
    group: www-data

- name: restart apache
  service:
    name: apache2
    state: restarted
